# Generated by Django 4.2.3 on 2023-07-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_rename_name_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
