# Generated by Django 4.2.3 on 2023-07-29 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_alter_profile_profile_pic_withdrawal_deposit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
