# Generated by Django 4.2.3 on 2023-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_rename_user_profile_deposit_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
