# Generated by Django 4.2.3 on 2023-08-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0012_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='mining.profile'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referral_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='successful_referrals',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
