# Generated by Django 4.2.3 on 2023-08-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0014_withdrawal_pin_withdrawal_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
