# Generated by Django 4.2.3 on 2023-08-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0016_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='mining.profile'),
        ),
    ]
